apiVersion: 1
datasources:
  - name: VeloAI
    type: postgres
    url: veloai-postgres:5432
    database: veloai
    user: veloai
    secureJsonData:
      password: $POSTGRES_PASSWORD
    jsonData:
      sslmode: disable
      timescaledb: false
