apiVersion: 1
datasources:
  - name: VeloAI
    uid: veloai
    type: postgres
    access: proxy
    url: veloai-postgres:5432
    user: veloai
    orgId: 1
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
    jsonData:
      database: veloai
      sslmode: disable
      timescaledb: false
      postgresVersion: 1500
    editable: true
    isDefault: true
