"""Ride with GPS API client + activity sync.

Auth is two static headers (api key + auth token) generated by the user on
ridewithgps.com -> account settings -> developers. Incremental sync uses the
/sync.json change feed with a server-issued cursor; see the design spec at
docs/superpowers/specs/2026-06-10-rwgps-activity-source-design.md.
"""

import os
import time
from datetime import datetime, timezone, timedelta

import requests

API_BASE = "https://ridewithgps.com/api/v1"

CYCLING_PREFIXES = ("cycling:", "e_biking:")


def _headers() -> dict:
    return {
        "x-rwgps-api-key": os.environ["RWGPS_API_KEY"],
        "x-rwgps-auth-token": os.environ["RWGPS_AUTH_TOKEN"],
    }


def _request_with_retry(method, url, max_retries=3, **kwargs):
    """Make an HTTP request with exponential backoff on 429."""
    kwargs.setdefault("timeout", 30)
    for attempt in range(max_retries + 1):
        resp = method(url, **kwargs)
        # Only sleep+retry if there's an attempt left — sleeping on the final
        # 429 just blocks the caller for minutes before returning the 429 anyway.
        if resp.status_code == 429 and attempt < max_retries:
            wait = min(60 * (2 ** attempt), 900)  # max 15 min
            print(f"[rwgps] Rate limited (429), waiting {wait}s (attempt {attempt + 1})")
            time.sleep(wait)
            continue
        return resp
    return resp  # unreachable (loop returns on the final attempt), kept defensively


def fetch_sync_items(since: str) -> tuple[list, str]:
    """GET /sync.json — trip change events since the given ISO 8601 datetime.

    Returns (trip items, server datetime to store as the next cursor).
    Non-trip items (routes) are filtered out.

    The sync endpoint is NOT paginated: a single request returns every item
    changed since `since` (`since=1970-01-01` returns the whole library), and
    `meta.rwgps_datetime` is the high-water-mark cursor for that complete
    response — not a page boundary. This is the canonical RWGPS workflow
    ("download every item in the response, store meta.rwgps_datetime, re-request
    with it"), so a single fetch + cursor advance drains the feed with no
    pagination loop. Verified against the RWGPS OpenAPI spec (no page/page_size
    params on this endpoint) and the published developer docs.
    """
    resp = _request_with_retry(
        requests.get,
        f"{API_BASE}/sync.json",
        headers=_headers(),
        params={"since": since, "assets": "trips"},
    )
    if resp.status_code == 401:
        print("[rwgps] auth failed — regenerate the auth token at "
              "ridewithgps.com → account settings → developers")
    resp.raise_for_status()
    body = resp.json()
    items = [i for i in body.get("items", []) if i.get("item_type") == "trip"]
    cursor = body.get("meta", {}).get("rwgps_datetime")
    if not cursor:
        raise ValueError(f"[rwgps] sync response missing meta.rwgps_datetime: {str(body)[:200]}")
    return items, cursor


def fetch_trip(trip_id: int) -> dict:
    """GET /trips/{id}.json — full trip incl. track_points. {} on 404/403."""
    resp = _request_with_retry(
        requests.get,
        f"{API_BASE}/trips/{trip_id}.json",
        headers=_headers(),
    )
    if resp.status_code in (403, 404):
        return {}
    resp.raise_for_status()
    return resp.json().get("trip", {})


def _is_cycling(trip: dict) -> bool:
    """Cycling filter: activity_type prefix, falling back to fit_sport."""
    activity_type = trip.get("activity_type") or ""
    if activity_type:
        return activity_type.startswith(CYCLING_PREFIXES)
    return trip.get("fit_sport") == "cycling"


def _map_strava_type(trip: dict) -> str:
    """Map RWGPS activity_type to the Strava-equivalent type string so
    db.classify_activity() works unchanged across sources.

    activity_type is not guaranteed to be present on every trip response (some
    payloads only carry fit_sport). When it is absent we degrade to "Ride" —
    virtual/e-bike labelling is lost, but the trainer/indoor split is preserved
    via the is_stationary flag in _parse_trip, and the cycling filter falls back
    to fit_sport in _is_cycling, so no ride is dropped or mislabelled as outdoor.
    """
    activity_type = trip.get("activity_type") or ""
    if activity_type == "cycling:virtual":
        return "VirtualRide"
    if activity_type.startswith("e_biking:"):
        return "EBikeRide"
    return "Ride"


def _detect_device(trip: dict) -> str:
    """Detect recording device from RWGPS trip metadata (same heuristics
    as strava._detect_device, adapted to RWGPS field names)."""
    device_name = (trip.get("device") or "").lower()
    if "karoo" in device_name:
        return "karoo"
    if "watch" in device_name or "apple" in device_name:
        return "watch"
    if (trip.get("activity_type") or "") == "cycling:virtual" \
            or "zwift" in (trip.get("name") or "").lower():
        return "zwift"
    return "unknown"


def _parse_trip(trip: dict) -> dict:
    """Convert an RWGPS trip detail response to our DB format.

    Caller must pass a non-empty trip dict (fetch_trip returns {} on 403/404
    — check truthiness first); trip["id"] is accessed unguarded.

    The trip-DETAIL endpoint (GET /trips/{id}.json) nests sensor aggregates
    under a `metrics` object: metrics.hr / metrics.watts / metrics.cad each
    carry avg/max, plus metrics.movingTime / metrics.duration / metrics.calories.
    They are NOT top-level (verified against the live API and two reference
    clients — howitt and SteveWinward). distance, elevation_gain, departed_at
    and is_stationary ARE top-level. The trips LIST endpoint instead exposes the
    metrics top-level, so we read `metrics` first and fall back to top-level —
    both shapes parse correctly.

    avg_speed_kmh is computed from distance/moving_time because the API does
    not document the avg_speed field's units. suffer_score has no RWGPS
    equivalent and stays None (the upsert never overwrites it from RWGPS data).
    """
    m = trip.get("metrics") or {}

    def _metric(channel, key):
        sub = m.get(channel)
        return sub.get(key) if isinstance(sub, dict) else None

    distance_m = trip.get("distance") or 0
    duration_s = (m.get("movingTime") or m.get("duration")
                  or trip.get("moving_time") or trip.get("duration") or 0)
    avg_speed_kmh = round(distance_m / duration_s * 3.6, 2) if duration_s else 0.0
    activity_type = trip.get("activity_type") or ""
    return {
        "rwgps_id": trip["id"],
        "name": trip.get("name", ""),
        "date": trip.get("departed_at"),
        "distance_m": distance_m,
        "duration_s": duration_s,
        "elevation_m": trip.get("elevation_gain", 0),
        "avg_hr": _metric("hr", "avg") or trip.get("avg_hr"),
        "max_hr": _metric("hr", "max") or trip.get("max_hr"),
        "avg_power": _metric("watts", "avg") or trip.get("avg_watts"),
        "max_power": _metric("watts", "max") or trip.get("max_watts"),
        "avg_cadence": _metric("cad", "avg") or trip.get("avg_cad"),
        "avg_speed_kmh": avg_speed_kmh,
        "calories": m.get("calories") or trip.get("calories"),
        "suffer_score": None,
        "device": _detect_device(trip),
        "strava_type": _map_strava_type(trip),
        # RWGPS marks trainer/turbo rides with the top-level `is_stationary` flag
        # (verified against the live API and four reference clients — NOT
        # `stationary`). `activity_type == "cycling:indoor"` is a secondary signal
        # that only fires when activity_type is present.
        "trainer": bool(trip.get("is_stationary")) or activity_type == "cycling:indoor",
    }


def _parse_track_points(points: list) -> list:
    """Convert RWGPS track_points to stream point dicts.

    RWGPS keys: t = unix epoch s, x = lng, y = lat, e = elevation m,
    s = speed km/h, h = HR bpm, c = cadence rpm, p = power W.
    Temperature (T) is dropped — no column for it.
    """
    if not points:
        return []
    t0 = points[0].get("t")
    if t0 is None:
        return []
    out = []
    for pt in points:
        t = pt.get("t")
        if t is None:
            continue
        out.append({
            "time_offset": int(t - t0),
            "hr": pt.get("h"),
            "power": pt.get("p"),
            "cadence": pt.get("c"),
            "speed_kmh": pt.get("s"),
            "altitude_m": pt.get("e"),
            "lat": pt.get("y"),
            "lng": pt.get("x"),
        })
    return out


def _process_trip_item(conn, item: dict, departed_after: datetime = None) -> bool:
    """Fetch, filter, parse, and store one created/updated trip.
    Returns True if the trip was ingested."""
    from db import upsert_activity, upsert_streams

    trip = fetch_trip(item["item_id"])
    if not trip:
        print(f"  [rwgps] Trip {item['item_id']} not accessible — skipped")
        return False
    if not _is_cycling(trip):
        kind = trip.get("activity_type") or trip.get("fit_sport") or "unknown"
        print(f"  ⏭ Skipping {trip.get('name', '?')} ({kind})")
        return False
    # A trip must have a parseable start time. A missing/garbage departed_at is a
    # deterministic data error and is skipped at the source: storing it would
    # create a dateless ride, and a non-ISO string makes find_duplicate's
    # ::timestamptz cast raise a psycopg2 DataError — which the sync loop cannot
    # tell apart from a transient failure, so it would withhold the cursor and
    # wedge all ingestion permanently. Skip it like a 404/non-cycling trip.
    departed = trip.get("departed_at")
    try:
        departed_dt = datetime.fromisoformat((departed or "").replace("Z", "+00:00"))
    except (ValueError, TypeError, AttributeError):
        print(f"  [rwgps] Skipping {trip.get('name', '?')} — missing/invalid departed_at ({departed!r})")
        return False
    # Normalise to UTC-aware before any comparison. A tz-naive departed_at (no Z,
    # no offset) parses fine but `naive < aware` raises TypeError against the
    # tz-aware backfill cutoff — and that TypeError would be swallowed by the
    # permanent-skip branch in sync_activities, silently dropping the ride during
    # bounded backfill (departed_after is None when polling, which masks it).
    if departed_dt.tzinfo is None:
        departed_dt = departed_dt.replace(tzinfo=timezone.utc)
    if departed_after is not None and departed_dt < departed_after:
        print(f"  ⏭ Skipping {trip.get('name', '?')} — departed before backfill window")
        return False

    data = _parse_trip(trip)
    streams = _parse_track_points(trip.get("track_points") or [])
    activity_id, streams_preserved = upsert_activity(conn, data)
    if streams and not streams_preserved:
        upsert_streams(conn, activity_id, streams)
    print(f"  → {data['name']} ({(data.get('date') or '')[:10]}) — {(data.get('distance_m') or 0)/1000:.1f}km")
    return True


def _handle_sync_item(conn, item: dict, departed_after, handle_rwgps_deletion) -> str:
    """Process one sync item. Returns 'ingested' | 'deleted' | 'skipped'.

    Raises on a transient failure (network/5xx/DB/JSON-decode) and on
    deterministic per-item data errors (KeyError/TypeError) — the caller
    classifies them.
    """
    if item.get("action") == "deleted":
        outcome = handle_rwgps_deletion(conn, item["item_id"])
        if outcome == "deleted":
            print(f"  ✕ Trip {item['item_id']} deleted on RWGPS — removed")
            return "deleted"
        if outcome == "unlinked":
            print(f"  [rwgps] Trip {item['item_id']} deleted on RWGPS — kept (also on Strava)")
        return "skipped"
    time.sleep(1.0)  # rate limit courtesy
    return "ingested" if _process_trip_item(conn, item, departed_after) else "skipped"


def sync_activities(conn, since: str = None, departed_after: datetime = None) -> tuple[int, int]:
    """Process the RWGPS sync feed. Returns (ingested, deleted) counts.

    since: explicit ISO cursor; defaults to the persisted sync_state cursor.
    departed_after: backfill cutoff — trips that departed earlier are skipped
    (sync.json keys on interaction time, not ride time).

    Items are processed in chronological order and the cursor is checkpointed
    after each fully-completed timestamp group. A *transient* failure
    (network/5xx/DB/JSON-decode) stops the pass but keeps the cursor at the last
    completed group, so the next cycle resumes there instead of discarding the
    whole pass — this lets a large/full-history backfill make durable forward
    progress and converge, rather than re-fetching the entire library every
    cycle until a (statistically unlikely) zero-failure pass. Grouping by item
    datetime keeps the checkpoint safe whether the feed's `since` is inclusive
    or exclusive: a datetime is only checkpointed once every item sharing it has
    been handled. Permanent conditions never block progress — 404/403 trips,
    non-cycling, outside the window, and deterministic per-item data errors
    (KeyError/TypeError from malformed trip/track-point/sync data) are skipped
    rather than replayed. (ValueError is treated as transient: a truncated-
    response JSONDecodeError is a ValueError subclass and is retryable.)
    """
    from db import get_sync_state, set_sync_state, handle_rwgps_deletion

    if since is None:
        since = get_sync_state(conn, "rwgps_last_sync_datetime") or "1970-01-01T00:00:00Z"

    items, server_datetime = fetch_sync_items(since)
    print(f"[rwgps] {len(items)} trip events since {since}")

    # Chronological order so the cursor can be checkpointed per completed group.
    items.sort(key=lambda it: it.get("datetime") or "")

    ingested = 0
    deleted = 0
    checkpoint = None       # latest item datetime with every item <= it handled
    transient = False
    idx = 0
    total = len(items)
    while idx < total and not transient:
        group_dt = items[idx].get("datetime") or ""
        j = idx
        group_done = True
        while j < total and (items[j].get("datetime") or "") == group_dt:
            item = items[j]
            try:
                result = _handle_sync_item(conn, item, departed_after, handle_rwgps_deletion)
                if result == "ingested":
                    ingested += 1
                elif result == "deleted":
                    deleted += 1
            except (KeyError, TypeError) as e:
                # Deterministic data error — skip like a 404; doesn't block the group.
                print(f"  [rwgps] Skipping item {item.get('item_id')} — unprocessable ({type(e).__name__}: {e})")
            except Exception as e:
                # Transient — stop the pass; the cursor keeps the last completed group.
                print(f"  [rwgps] Failed to process item {item.get('item_id')}: {e}")
                transient = True
                group_done = False
                break
            j += 1
        if group_done:
            checkpoint = group_dt
            idx = j

    if not transient:
        set_sync_state(conn, "rwgps_last_sync_datetime", server_datetime)
    elif checkpoint:
        set_sync_state(conn, "rwgps_last_sync_datetime", checkpoint)
        print(f"[rwgps] transient failure — cursor checkpointed to {checkpoint}, remainder retries next cycle")
    else:
        print("[rwgps] transient failure before any progress — cursor unchanged, batch retries next cycle")
    return ingested, deleted


def backfill(conn, months: int = 12) -> int:
    """Initial RWGPS import. months=0 = full history.

    Uses the same sync feed as polling: since=1970 replays the entire library
    as 'created' events. For a bounded window the departed_at cutoff prunes
    old rides that were merely edited recently.
    """
    if months == 0:
        print("[rwgps] Backfilling FULL history")
        ingested, _ = sync_activities(conn, since="1970-01-01T00:00:00Z")
        return ingested
    cutoff = datetime.now(timezone.utc) - timedelta(days=months * 30)
    since = cutoff.strftime("%Y-%m-%dT%H:%M:%SZ")
    print(f"[rwgps] Backfilling {months} months (since {cutoff.date()})")
    ingested, _ = sync_activities(conn, since=since, departed_after=cutoff)
    return ingested
